In [5]:
import pandas as pd
music_data = pd.read_csv('music.csv')
X = music_data.drop(columns=['genre'])
y = music_data.drop(columns=['age', 'gender'])
y

        genre
0      HipHop
1      HipHop
2      HipHop
3        Jazz
4        Jazz
5        Jazz
6   Classical
7   Classical
8   Classical
9       Dance
10      Dance
11      Dance
12   Acoustic
13   Acoustic
14   Acoustic
15  Classical
16  Classical
17  Classical